### ISSUE TITLE
关于安装问题

### ISSUE THREAD

**Issue by huoji1990** [dory-engine/dory-ctl#1]
尝试安装了一下，但没有搞定。
安装方式看似简单，但确过于全家桶了，一般场景中nexus、gitlab等都是已经存在的，只需要安装dory-engine服务，将其串联起来即可，但研究了半天，没有搞定如何只安装dory-engine。
是否可以优化安装文档，或优化配置方式

**Comment by cookeem** [comment]
@huoji1990 确实本来不应该安装这些全家桶的，但是如果从头开始，确实需要这些devops的组件，所以doryctl为了简单把这些组件的安装也包含进去了。
doryctl install script方式就是手动方式，他会生成所有配置文件和说明，你自己修改相关配置文件和参数，这种情况下你可以使用已有的nexus、gitlab、harbor来进行安装，但是你需要手工修改dory-core的config.yaml配置文件，来连接nexus、gitlab、harbor。

**Comment by cookeem** [comment]
@huoji1990 https://doryengine.com/docs/quick-start/install-in-kubernetes/ 这里有完成的安装视频演示。你的问题应该是安装配置文件配置有问题，你可以把你的配置贴出来看看。

**Comment by huoji1990** [comment]
是不是比如gitlab、nexus、k8s等其中有没有配置的，dory-core服务就会启动不起来？

**Comment by cookeem** [comment]
`doryctl install script`会自动创建所有组件的部署脚本，你可以选择性的删除gitlab、nexus对应的组件。不过nexus我不建议你用自己的，因为里边有很多设置跟dory的构建依赖配置绑定在一起了，你可以手工修改dory的配置文件，但需要改的地方很多。
doryctl其实做的事情就是两个部分：1、部署好所有的devops组件；2、根据这些组件的密钥，配置好dory-core的config.yaml配置文件。当然第二步你可以自己手工修改config.yaml文件就好，都能启动的。

**Comment by cookeem** [comment]
如果你具体还有一些问题，可以加我微信：cookeem
