### ISSUE TITLE
文档不够齐全

### ISSUE THREAD

**Issue by vicnoah** [dory-engine/dory-ctl#4]
可以增加一些配置及使用的示例吗？安装完成后发现使用上并不像想象中简单，可能我当时配置上也不是特别正确，创建项目后流水线触发等不太正常。
另外官网咋变成博客了啊，文档都没了，请问是不维护了吗？

**Comment by cookeem** [comment]
@vicnoah 官网正在备案一个新域名，只能临时搞了一个用于备案，备案结束就可以恢复正常了。

部署成功了对吧？触发流水线出现什么问题？这里发一下？因为这几个星期在更新一个大版本，所以暂时没有更新开源版。抱歉哈

**Comment by cookeem** [comment]
@vicnoah bilibili上有很多演示视频的： https://space.bilibili.com/511582631?spm_id_from=333.788.b_765f7570696e666f.2
其实dory的简单主要体现在开发人员不再需要编写k8s的yaml部署文件，不再需要编写任何流水线脚本。跟jenkins、gitlab、argo的最大差别就是在这里。
